[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL,VITE_SOCKET_URL,PORT,NODE_ENV"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
