[build]
  command = "npm install"
  functions = "functions"
  publish = "public" # Create an empty public folder if needed or use a dummy

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL,VITE_SOCKET_URL"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
